version: "3.8"

services:
  tameng-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tameng_digital_guard
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api # Ganti dengan URL produksi nanti
    networks:
      - tameng-network

networks:
  tameng-network:
    driver: bridge
